name: Run vid.sh in 20 Parallel Jobs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-vid:
    name: Job ${{ matrix.job_id }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_id: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make vid.sh executable and run
        run: chmod +x vid.sh && ./vid.sh
